// <auto-generated />
using DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240620124830_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "The system automatically resends the e-ticket that has not been successfully delivered to the client. E-tickets can also be found in “my tickets” tab once you are logged on to your account.",
                            Title = "I didn’t receive my mTicket. Can you re-send it?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Go Bus abides by safety protocols and security standards, under the auspices of the Ministry of Transportation. We depend on a modern fleet of buses, whose speed is electronically controlled by the agency without drivers’ intervention. We have a whole staff of highly-trained drivers to maintain these protocols and standards.",
                            Title = "Does the company stipulate a maximum speed for divers?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "You can easily browse the different trip times and dates, however, in order to book a ticket, you need to be registered with Go Bus.",
                            Title = "Do I need to register to use Go Bus?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Go Bus is keen on its staff skills and capacity development. The company always seeks to enhance the skills of drivers and employees. Therefore, we have recently inked a protocol with the Egyptian Road Safety Training Centre to train 80% of our drivers, which is a testament of our vision to develop drivers’ skills and ensure our customers’ safety and satisfaction.",
                            Title = "What are Go Bus driver skill enhancement program and customer safety and satisfaction strategy?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Go Bus’s strategy considering the customer on the top of our priorities and our endeavor towards offering high-quality services are manifested in the difference Go Bus continues to make in Egypt’s transportation system in general through its peerless control room, which monitors its fleet across Egypt 24/7. The purpose of this room is to offer real-time monitoring system for drivers and passengers’ safety, and records drivers’ traffic offences, ensuring rapid crisis response and management.",
                            Title = "Earlier you announced that Go Bus owns a central control room, what is its value for the company?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Once you have entered your mobile number while booking it can’t be changed for that particular transaction. You can however, go back and change your mobile number for further transactions. To board the bus, your name has to match the name on the e-ticket.",
                            Title = "I entered the wrong mobile number while booking. Can I get my mTicket on a different number?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "You can easily access “my tickets” tab once you are logged onto the website, to view your history of tickets. You can use this history to view your e-ticket and board the bus.",
                            Title = "I’ve lost my ticket. What should I do now?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "No, it is not mandatory to take a printout of the ticket, however, you need to have a copy of the ticket with your name on it on your device, or have the e-ticket to board the bus.",
                            Title = "Is it mandatory to take a printout of the ticket?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Go Bus’ fleet is very distinctive and is not found in any other transportation company. When booking online, it is quick and easy with no need to go to the station to make a booking.",
                            Title = "What are the advantages of purchasing a bus ticket with Go Bus?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Booking online does not cost you more, to the contrary, it is time effective and quick.",
                            Title = "Does booking online cost me more?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
