// <auto-generated />
using System;
using DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240619202714_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Data.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageURL = "https://lp-cms-production.imgix.net/news/2019/02/Cairo-market.jpg",
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = 2,
                            ImageURL = "https://go-bus.com:8181/wp-content/uploads/2019/04/Sharm-hero.jpg",
                            Name = "Red Sea"
                        },
                        new
                        {
                            Id = 3,
                            ImageURL = "https://go-bus.com:8181/wp-content/uploads/2019/04/sokhna-hero-1.jpg",
                            Name = "South Sinai"
                        },
                        new
                        {
                            Id = 4,
                            ImageURL = "https://go-bus.com:8181/wp-content/uploads/2018/05/Alex-hero.jpg",
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 5,
                            ImageURL = "https://www.carolsbeaurivage.com/medias/slide/big/5/img-9257.jpg",
                            Name = "North Coast"
                        },
                        new
                        {
                            Id = 6,
                            ImageURL = "https://planetofhotels.com/guide/sites/default/files/styles/paragraph__live_banner__lb_image__1880bp/public/live_banner/Suez.jpg",
                            Name = "Suez"
                        },
                        new
                        {
                            Id = 7,
                            ImageURL = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/7d/c0/f6/qena.jpg?w=500&h=300&s=1",
                            Name = "Qena"
                        },
                        new
                        {
                            Id = 8,
                            ImageURL = "https://media.odyfolio.com/pho/145/uae-uae-al-gharbia-liwa-desert-qasr-al-sarab-hotel_m-1-169.jpeg",
                            Name = "Gharbia"
                        },
                        new
                        {
                            Id = 9,
                            ImageURL = "https://cdn.britannica.com/10/126710-050-8E814ED9/building-Suez-Canal-Authority-Port-Said-Egypt.jpg",
                            Name = "Port Said"
                        },
                        new
                        {
                            Id = 10,
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/4/4d/AsyutUniversityMainBldg.jpg",
                            Name = "Assiut"
                        },
                        new
                        {
                            Id = 11,
                            ImageURL = "https://facts.net/wp-content/uploads/2023/07/40-facts-about-menia-1689735034.jpeg",
                            Name = "Menia"
                        },
                        new
                        {
                            Id = 12,
                            ImageURL = "https://www.introducingegypt.com/f/egipto/egipto/guia/luxor-m.jpg",
                            Name = "Luxor"
                        },
                        new
                        {
                            Id = 13,
                            ImageURL = "https://t3.ftcdn.net/jpg/03/63/61/66/360_F_363616600_zenx3HVCXEVDAYhBYhYglFYU9xTRYKMO.jpg",
                            Name = "Dakahlia"
                        },
                        new
                        {
                            Id = 14,
                            ImageURL = "https://mercure.accor.com/local-stories/media/ismailia_desk.jpg",
                            Name = "Ismailia"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.EndBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("EndBranches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "9 Ramses St. (Railroad Company) in front of Ramses Train station",
                            DestinationId = 1,
                            Name = "Ramses",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 2,
                            Address = "The Tourist walkway west of Somid, the central axis in front of 6 october City Hall",
                            DestinationId = 1,
                            Name = "6 october",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Madinaty Gate 1",
                            DestinationId = 1,
                            Name = "Madinaty",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 El Galaa St. AbdelMoneim Riyad square next to Ramses Hilton Hotel Maspero Mall.",
                            DestinationId = 1,
                            Name = "AbdelMoneim Riyad",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Next to Safaga Port Open from 7 am to 12 am",
                            DestinationId = 2,
                            Name = "Safaga",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Next to CIB, 68 El Souq St. - In front of El Gamee Bank . Open from 8 am to 8 pm",
                            DestinationId = 2,
                            Name = "Marsa Alam",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Bike and in front of El Gouna School Open from 8.30 am to 12.30 am",
                            DestinationId = 2,
                            Name = "El Gouna",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Inside of Orascom Mall Makadi. Open from 9 am to 7 pm",
                            DestinationId = 2,
                            Name = "Makadi",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Downtown next to Best Way Market beside the cinema. Getting on and off of the bus from the parking at the waiting hall of Pizatzza Village not from in front of the office. Open from 9 am to 9 pm.",
                            DestinationId = 2,
                            Name = "Sahl Hasheesh",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 10,
                            Address = "ElNasr St. next to The Red Sea Hospital and ElHadidy Market and the old Fire station. Open 24 hrs.",
                            DestinationId = 2,
                            Name = "Main Hurghada Office",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Located at Adam Abu Sawira Cafeteria is located directly on the road",
                            DestinationId = 3,
                            Name = "Ras Sader Station",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 12,
                            Address = "La Hacienda",
                            DestinationId = 3,
                            Name = "La Hacienda",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 13,
                            Address = "El Mashraba St. beside Dahab Plaza Hotel next to Maabar ElSeel Bride. Open from 7 am to 2 am",
                            DestinationId = 3,
                            Name = "Dahab",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Shams Mall in front of Elwataneya Gas station - before Sharm ElSheikh International Hospital (International Haram Hospital)",
                            DestinationId = 3,
                            Name = "Sharm",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 15,
                            Address = "45 St. Miami Corniche - Next to ElKataa Fish Open from 10 am to 1 am",
                            DestinationId = 4,
                            Name = "Miami",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Inside of of the New Station , there are two offices in the building - Bus station is at platform 6 Open 24 hrs.",
                            DestinationId = 4,
                            Name = "Moharam Bek",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Marina 7 : Before Marina 7 gate with 200 m - next to El Ahly Bank and Allam Auto Motors - the office is on the opposite side of the gate",
                            DestinationId = 5,
                            Name = "Marina 7",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Stella Sidi Abdelrahman ; Infront of Stella Walk mall Sidi Abdelrahman",
                            DestinationId = 5,
                            Name = "Sidi Abdelrahman",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Marassi : After the traffic point of Sidi Abdelrahman with 300 m in the direction of Alexandria next to ElGezira Coach",
                            DestinationId = 5,
                            Name = "Marassi",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 20,
                            Address = "At km 2 - next to West Delta Travel station",
                            DestinationId = 5,
                            Name = "Marsa Matruh",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 21,
                            Address = "In Front of El Mahmal Supermarket at Porto Sokhna Entrance Getting on and off of the bus from Gate 2 of Porto EL Sokhna beneath the pedestrian bridge in front of Ragab Sons Supermarket. Go Mini station is in front of Mcdonalds near the office. Open from 6 am to 11 pm",
                            DestinationId = 6,
                            Name = "Porto EL Sokhna",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Next to Sidi Abdelraheem Mosque and El Soltan store. Open 24 hrs",
                            DestinationId = 7,
                            Name = "Qena Sidi Abdelraheem",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 23,
                            Address = "6 Abdel el hay shahin Mansheya El-Bakry El Mahalla 1st Police Department",
                            DestinationId = 8,
                            Name = "Mahalla",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 24,
                            Address = "1 Abdel wahab St. with el fateh infront of wholesale market position",
                            DestinationId = 8,
                            Name = "Tanta",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Downtown mall -next to the fish market - in front of (Gawaher El Bon)",
                            DestinationId = 9,
                            Name = "Port Said Downtown",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 26,
                            Address = "El Helaly St.at the beginning of El Helaly bridge next to the Syndicate Of Applicators",
                            DestinationId = 10,
                            Name = "El Helaly",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Shahin neighberhood, 23 Cairo - Aswan agriculture road",
                            DestinationId = 11,
                            Name = "Minya",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 28,
                            Address = "17 Ramses St. Next to the train station. Open 24 hrs",
                            DestinationId = 12,
                            Name = "Luxor",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 29,
                            Address = "El Geish St. next to Cairo bank infront of East Delta Travel",
                            DestinationId = 13,
                            Name = "El Mansoura",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Drop off and pick up at El Gomhoria St.",
                            DestinationId = 14,
                            Name = "Ismailia",
                            Phone = "01093996245"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.StartBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("StartBranches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "9 Ramses St. (Railroad Company) in front of Ramses Train station",
                            DestinationId = 1,
                            Name = "Ramses",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 2,
                            Address = "The Tourist walkway west of Somid, the central axis in front of 6 october City Hall",
                            DestinationId = 1,
                            Name = "6 october",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Madinaty Gate 1",
                            DestinationId = 1,
                            Name = "Madinaty",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4 El Galaa St. AbdelMoneim Riyad square next to Ramses Hilton Hotel Maspero Mall.",
                            DestinationId = 1,
                            Name = "AbdelMoneim Riyad",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Next to Safaga Port Open from 7 am to 12 am",
                            DestinationId = 2,
                            Name = "Safaga",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Next to CIB, 68 El Souq St. - In front of El Gamee Bank . Open from 8 am to 8 pm",
                            DestinationId = 2,
                            Name = "Marsa Alam",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Bike and in front of El Gouna School Open from 8.30 am to 12.30 am",
                            DestinationId = 2,
                            Name = "El Gouna",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Inside of Orascom Mall Makadi. Open from 9 am to 7 pm",
                            DestinationId = 2,
                            Name = "Makadi",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Downtown next to Best Way Market beside the cinema. Getting on and off of the bus from the parking at the waiting hall of Pizatzza Village not from in front of the office. Open from 9 am to 9 pm.",
                            DestinationId = 2,
                            Name = "Sahl Hasheesh",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 10,
                            Address = "ElNasr St. next to The Red Sea Hospital and ElHadidy Market and the old Fire station. Open 24 hrs.",
                            DestinationId = 2,
                            Name = "Main Hurghada Office",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Located at Adam Abu Sawira Cafeteria is located directly on the road",
                            DestinationId = 3,
                            Name = "Ras Sader Station",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 12,
                            Address = "La Hacienda",
                            DestinationId = 3,
                            Name = "La Hacienda",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 13,
                            Address = "El Mashraba St. beside Dahab Plaza Hotel next to Maabar ElSeel Bride. Open from 7 am to 2 am",
                            DestinationId = 3,
                            Name = "Dahab",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Shams Mall in front of Elwataneya Gas station - before Sharm ElSheikh International Hospital (International Haram Hospital)",
                            DestinationId = 3,
                            Name = "Sharm",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 15,
                            Address = "45 St. Miami Corniche - Next to ElKataa Fish Open from 10 am to 1 am",
                            DestinationId = 4,
                            Name = "Miami",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Inside of of the New Station , there are two offices in the building - Bus station is at platform 6 Open 24 hrs.",
                            DestinationId = 4,
                            Name = "Moharam Bek",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Marina 7 : Before Marina 7 gate with 200 m - next to El Ahly Bank and Allam Auto Motors - the office is on the opposite side of the gate",
                            DestinationId = 5,
                            Name = "Marina 7",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Stella Sidi Abdelrahman ; Infront of Stella Walk mall Sidi Abdelrahman",
                            DestinationId = 5,
                            Name = "Sidi Abdelrahman",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Marassi : After the traffic point of Sidi Abdelrahman with 300 m in the direction of Alexandria next to ElGezira Coach",
                            DestinationId = 5,
                            Name = "Marassi",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 20,
                            Address = "At km 2 - next to West Delta Travel station",
                            DestinationId = 5,
                            Name = "Marsa Matruh",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 21,
                            Address = "In Front of El Mahmal Supermarket at Porto Sokhna Entrance Getting on and off of the bus from Gate 2 of Porto EL Sokhna beneath the pedestrian bridge in front of Ragab Sons Supermarket. Go Mini station is in front of Mcdonalds near the office. Open from 6 am to 11 pm",
                            DestinationId = 6,
                            Name = "Porto EL Sokhna",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Next to Sidi Abdelraheem Mosque and El Soltan store. Open 24 hrs",
                            DestinationId = 7,
                            Name = "Qena Sidi Abdelraheem",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 23,
                            Address = "6 Abdel el hay shahin Mansheya El-Bakry El Mahalla 1st Police Department",
                            DestinationId = 8,
                            Name = "Mahalla",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 24,
                            Address = "1 Abdel wahab St. with el fateh infront of wholesale market position",
                            DestinationId = 8,
                            Name = "Tanta",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Downtown mall -next to the fish market - in front of (Gawaher El Bon)",
                            DestinationId = 9,
                            Name = "Port Said Downtown",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 26,
                            Address = "El Helaly St.at the beginning of El Helaly bridge next to the Syndicate Of Applicators",
                            DestinationId = 10,
                            Name = "El Helaly",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Shahin neighberhood, 23 Cairo - Aswan agriculture road",
                            DestinationId = 11,
                            Name = "Minya",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 28,
                            Address = "17 Ramses St. Next to the train station. Open 24 hrs",
                            DestinationId = 12,
                            Name = "Luxor",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 29,
                            Address = "El Geish St. next to Cairo bank infront of East Delta Travel",
                            DestinationId = 13,
                            Name = "El Mansoura",
                            Phone = "01093996245"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Drop off and pick up at El Gomhoria St.",
                            DestinationId = 14,
                            Name = "Ismailia",
                            Phone = "01093996245"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime");

                    b.Property<int>("EndBranchId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal");

                    b.Property<int>("StartBranchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndBranchId");

                    b.HasIndex("StartBranchId");

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("DAL.Data.Models.EndBranch", b =>
                {
                    b.HasOne("DAL.Data.Models.Destination", "Destination")
                        .WithMany("EndBranchs")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("DAL.Data.Models.StartBranch", b =>
                {
                    b.HasOne("DAL.Data.Models.Destination", "Destination")
                        .WithMany("StartBranchs")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("DAL.Data.Models.Trip", b =>
                {
                    b.HasOne("DAL.Data.Models.EndBranch", "EndBranch")
                        .WithMany("Trips")
                        .HasForeignKey("EndBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.Data.Models.StartBranch", "StartBranch")
                        .WithMany("Trips")
                        .HasForeignKey("StartBranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EndBranch");

                    b.Navigation("StartBranch");
                });

            modelBuilder.Entity("DAL.Data.Models.Destination", b =>
                {
                    b.Navigation("EndBranchs");

                    b.Navigation("StartBranchs");
                });

            modelBuilder.Entity("DAL.Data.Models.EndBranch", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DAL.Data.Models.StartBranch", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
